apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: tu-imagen-de-webapp
        ports:
        - containerPort: 80
        volumeMounts:
        - name: webapp-storage
          mountPath: /usr/share/nginx/html
      volumes:
      - name: webapp-storage
        persistentVolumeClaim:
          claimName: webapp-pvc
